-- Creacion de procedimiento almacenado
-- Un procedimiento almacenado que ingrese el tipo de seguro por parámetro, 
-- para ver cuantos seguros se han vendido por año.
CREATE OR REPLACE FUNCTION VENTA_SEGURO(VARCHAR) RETURNS SETOF "record"
AS 
$BODY$

	SELECT
		EXTRACT(YEAR FROM AGENTE_VENDEDOR.FECH_CONTR) AS FECHA,
		COUNT(REGISTRO.ID_AGENT) AS NUMERO_PLANES
	FROM REGISTRO
        INNER JOIN TIPO_CONTRATO ON REGISTRO.ID_TIP = TIPO_CONTRATO.ID_TIP
		INNER JOIN AGENTE_VENDEDOR ON REGISTRO.ID_AGENT = AGENTE_VENDEDOR.ID_AGENT
	WHERE TIPO_CONTRATO.NOM_TIP = $1
	GROUP BY 1
	ORDER BY 1;

$BODY$
LANGUAGE SQL;

SELECT * FROM VENTA_SEGURO('Premium') 
AS ("fecha" DOUBLE PRECISION, "numero_planes" BIGINT);
