-- Creacion consultas
-- Histórico de ingresos por tipo de tipo de planes.
SELECT
	EXTRACT(YEAR FROM AGENTE_VENDEDOR.FECH_CONTR) AS FECHA,
	TIPO_CONTRATO.NOM_TIP AS TIPO_PLAN,
	COUNT(REGISTRO.ID_TIP) AS NUMERO_PLANES,
    COUNT(REGISTRO.ID_CLIEN) AS NUMERO_CLIENTES,
    SUM(PAGO.COSTO_PAGO) AS TOTAL_INGRESOS
FROM REGISTRO
	INNER JOIN TIPO_CONTRATO ON REGISTRO.ID_TIP = TIPO_CONTRATO.ID_TIP
	INNER JOIN PAGO ON REGISTRO.ID_REG = PAGO.ID_REG
	INNER JOIN AGENTE_VENDEDOR ON REGISTRO.ID_AGENT = AGENTE_VENDEDOR.ID_AGENT
GROUP BY 1, 2
ORDER BY 1 ASC;

-- Historicos de ventas de contratos por asesor.
SELECT
	EXTRACT(YEAR FROM AGENTE_VENDEDOR.FECH_CONTR) AS FECHA,
	AGENTE_VENDEDOR.NOM_AGENT AS NOMBRE_ASESOR,
    (SELECT 
	 	COUNT(ID_AGENT) 
	FROM REGISTRO 
	WHERE REGISTRO.ID_AGENT = AGENTE_VENDEDOR.ID_AGENT) AS NUMERO_PLANES,
    SUM(PAGO.COSTO_PAGO) AS TOTAL_INGRESOS
FROM REGISTRO
	INNER JOIN AGENTE_VENDEDOR ON REGISTRO.ID_AGENT = AGENTE_VENDEDOR.ID_AGENT
    INNER JOIN PAGO ON REGISTRO.ID_REG = PAGO.ID_REG
GROUP BY 1, 2, 3
ORDER BY 1 ASC;

-- Histórico de pagos que la institución está haciendo a los que están en jubilación.
SELECT 
	EXTRACT(YEAR FROM FECHA_PAGM) AS FECHA,
	INST_BANC AS NOMBRE_INSTITUCION,
    SUM(COSTO_PAGM) AS TOTAL_PAGO
FROM REGISTRO
	INNER JOIN PAGO_MENSUALIDAD ON REGISTRO.ID_REG = PAGO_MENSUALIDAD.ID_REG
GROUP BY 1, 2
ORDER BY 1 ASC;

-- Historial de numero de retiros de contratos por año
SELECT
	EXTRACT(YEAR FROM ESTADO.FECHA_EST) AS FECHA,
    COUNT(REGISTRO.ID_EST) AS NUMERO_RETIROS
FROM REGISTRO
	INNER JOIN ESTADO ON REGISTRO.ID_EST = ESTADO.ID_EST
WHERE ESTADO.ESTADO_EST = 'RETIRO'
GROUP BY 1
ORDER BY 1 ASC;
