-- Creacion de alter table para construir las relaciones de las tablas creadas

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_ID_LUGAR FOREIGN KEY (ID_LUGAR)
		REFERENCES LUGAR_DE_NACIMIENTO (ID_LUG)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PAGO_MENSUALIDAD
	ADD CONSTRAINT FK_ID_REGISTRO FOREIGN KEY (ID_REG)
		REFERENCES REGISTRO (ID_REG)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
        
ALTER TABLE PAGO
	ADD CONSTRAINT FK_ID_REGIS FOREIGN KEY (ID_REG)
		REFERENCES REGISTRO (ID_REG)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
        
ALTER TABLE REGISTRO
	ADD CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIEN)
		REFERENCES CLIENTE (ID_CLIEN)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
        
ALTER TABLE REGISTRO
	ADD CONSTRAINT FK_ID_ESTADO FOREIGN KEY (ID_EST)
		REFERENCES ESTADO (ID_EST)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
        
ALTER TABLE REGISTRO
	ADD CONSTRAINT FK_ID_AGENTE FOREIGN KEY (ID_AGENT)
		REFERENCES AGENTE_VENDEDOR (ID_AGENT)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
        
ALTER TABLE REGISTRO
	ADD CONSTRAINT FK_ID_TIPOC FOREIGN KEY (ID_TIP)
		REFERENCES TIPO_CONTRATO (ID_TIP)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
        
ALTER TABLE REGISTRO
	ADD CONSTRAINT FK_ID_LIQUIDACION FOREIGN KEY (ID_LIQ)
		REFERENCES LIQUIDACION (ID_LIQUI)
        ON DELETE RESTRICT ON UPDATE RESTRICT;